language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  domain: pitchbattles.herokuapp.com
  project: "./build/"
  api_key:
    secure: HeLuixT98mA/TuHRvqsAvcTQSwzP4xOWVDewKTEyUtjmCfDJz1XUKsii3EwCAKXkYJvCRFPHFUSAvBsG0QcaGGc7DmvkW9OoRHddWM9yenOXmzs1bj9nDWH/1qzz+qJTQIHhRPUbl+zw/rpVEMKjNG63S1stAgYlzFf6Mg93mmnkcgU4FLtuYK9YIl55zv8TVPfw6U7UoKR3pGsZGGjdo9fMwGiOzG3wb9/HAbvixVKnJt0HPZ54WmxTSCjpwiSsgeO0y/c6+vD99F/KU8Th1XnIdla8ZuUVDRAgzlf4LhcBCQOegNZBplK61NT0+64NLk60Kjrbb43Pu5NpnYg76bG1OIIAP5eQoxzoGED27uK+yGQV00hxTmHIehjqXbfBIhsz8/9EnF9I8d43uBWbP+guyFIZ3i3BQkdZ4sYTZPvbXb3Ts20FsbP1G2Kl7EapNPCzoTk/+2uI/BMWBLXb1DpJo/kLyps8545PmCRBIFErY4TRsmkXYuTW7TSoXn3CfjtLnDAt72OalRCRfaRM2nyR7Xxqa8PpfTs17ZD+4pnA55opa/N9MZSwZQZYFYso8hTk2j+W54s9urXnBsuQrm+V5qtutfAVCcBHCt39y904aB80te2NYbIeICMGD2qIc72C2V8PM3wI2jJoF5E2VnO3QazlCNv9G9HRkPwv2SI=
true:
  branch: master
